# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74d2d232c8ece92d60b836aeb77d35f931aca95a4b441d1f314ec91b12d919af8a7c197f64532a85a4b573a7dbed10eb02ed7b06be0003f6d7dfa2f22e8a2cc4

test:
  secret_key_base: 2356d2ad1a58d60c5eaf9aa735ff78d6e57c3ac357724d77870a398c38e1d9af4b72e669079163500916214a9baf12ff6898f543769b77a9a75ff2e7ecdcd68d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
